version: "3.7"


services:
  bot:
    container_name: bot
    build: ./bot
    volumes:
      - ./bot/src:/bot/src/
    environment:
      - VK_BOT_GROUP_TOKEN
      - L1_RPC_URL
      - ARBITRUM_RPC_URL
    command: python -m src
